### ISSUE TITLE
Please make options for custom element attribute

### ISSUE THREAD

**Issue by madedwi** [maykinmedia/dual-listbox#29]
Hi, 
First i would like to thank you for this library, this is great!
As my issue title, can you add options for custom element attribute?
So we can add custom class/data to button or search input. I think this is important for styling, so we're not overriding your style.

**Comment by JostCrow** [comment]
Yes that should be possible. I will let you know when it is done.

You are also allowed to make a pull request with the needed change. I you have some time to do so

**Comment by JostCrow** [comment]
All the elements should be exposed. This way it should be possible to add custom attributes to the element of choice.

```javascript
let dualListbox = new DualListbox('#select');

// Access the buttons:
dualListbox.add_button.setAttribute('a', 'a');
dualListbox.add_all_button.setAttribute('a', 'a');
dualListbox.remove_button.setAttribute('a', 'a');
dualListbox.remove_all_button.setAttribute('a', 'a');

// Access the search field:
dualListbox.search.classList.add('some_class');

// Access the list containers:
dualListbox.selectedList.setAttribute('a', 'a');
dualListbox.availableList.setAttribute('a', 'a');
```
Hopefully this will be enough to change the elements that you need to edit.

If this will be sufficient that would be great, since this will also help with the maintainability of the code. This will keep it nice and small

**Comment by JostCrow** [comment]
Closing this issue
